Changes for RavenDB 7 release (#822)
* Things are compiling

* Cluster wide transaction support for timeout storage

* Fix accidental rename

* Enabling timeouts feature

* Also singe instance

* Fix DocumentStoreManagerTests

* Approve new timeout file

* Let's see if changing the session timeout makes the test reliably pass

* Use Path property

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -14,13 +14,140 @@ on:
 env:
   DOTNET_NOLOGO: true
 jobs:
-  build:
+  setup:
     if:
       (github.event_name == 'pull_request_target' && github.event.pull_request.user.login == 'dependabot[bot]') ||
       (github.event_name == 'pull_request' && github.event.pull_request.user.login != 'dependabot[bot]') ||
       github.event_name == 'push' || github.event_name == 'workflow_dispatch'
+    name: Setup RavenDB Nodes
+    runs-on: ubuntu-20.04
+    outputs:
+      prefix: ${{ steps.setup-ravendb.outputs.prefix }}
+    steps:
+      - name: Check for secrets
+        env:
+          SECRETS_AVAILABLE: ${{ secrets.SECRETS_AVAILABLE }}
+        shell: pwsh
+        run: exit $(If ($env:SECRETS_AVAILABLE -eq 'true') { 0 } Else { 1 })
+      - name: Azure login
+        uses: azure/login@v1.4.1
+        with:
+          creds: ${{ secrets.AZURE_ACI_CREDENTIALS }}
+          enable-AzPSSession: true
+      - name: Setup RavenDB
+        id: setup-ravendb
+        shell: pwsh
+        run: |
+          $hostInfo = curl -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2021-02-01" | ConvertFrom-Json
+          $region = $hostInfo.compute.location
+          $license = '${{ secrets.RAVENDB_LICENSE }}'
+
+          function NewRavenDBNode {
+              param (
+                  $region,
+                  $prefix,
+                  $instanceId,
+                  $runnerOs,
+                  $commit
+              )
+
+              $hostname = "$prefix-$instanceId"
+
+              # echo will mess up the return value
+              Write-Debug "Creating RavenDB container $hostname in $region (This can take a while.)"
+
+              $containerImage = "ravendb/ravendb:5.3-ubuntu-latest"
+              $details = az container create --image $containerImage --name $hostname --location $region --dns-name-label $hostname --resource-group GitHubActions-RG --cpu 4 --memory 8 --ports 8080 38888 --ip-address public --environment-variables RAVEN_ServerUrl="http://0.0.0.0:8080" RAVEN_ServerUrl_Tcp="tcp://0.0.0.0:38888" RAVEN_PublicServerUrl="http://$($hostname).$($region).azurecontainer.io:8080" RAVEN_PublicServerUrl_Tcp="tcp://$($hostname).$($region).azurecontainer.io:38888" RAVEN_Setup_Mode="None" RAVEN_License_Eula_Accepted="true" RAVEN_Security_UnsecuredAccessAllowed="PublicNetwork" | ConvertFrom-Json
+              
+              # echo will mess up the return value
+              Write-Debug "Tagging container image"
+              $dateTag = "Created=$(Get-Date -Format "yyyy-MM-dd")"
+              $ignore = az tag create --resource-id $details.id --tags Package=RavenPersistence RunnerOS=$runnerOs Commit=$commit $dateTag
+
+              return $details.ipAddress.fqdn
+          }
+
+          $prefix = "psw-ravendb-$(Get-Random)"
+
+          echo "::set-output name=prefix::$prefix"
+
+          $fqdnRavenDB = @{ singlenode = ""; leader = ""; follower1 = ""; follower2 = "" }
+
+          $NewRavenDBNodeDef = $function:NewRavenDBNode.ToString()
+
+          @($fqdnRavenDB.keys) | ForEach-Object -Parallel {
+              $function:NewRavenDBNode = $using:NewRavenDBNodeDef
+              $region = $using:region
+              $prefix = $using:prefix
+              $detail = NewRavenDBNode $region $prefix $_ ${{ runner.os }} ${{ github.sha }}
+              $hashTable = $using:fqdnRavenDB
+              $hashTable[$_] = $detail
+          }
+
+          @($fqdnRavenDB.keys) | ForEach-Object -Parallel {
+              $startDate = Get-Date
+              $hashTable = $using:fqdnRavenDB
+              $tcpClient = New-Object Net.Sockets.TcpClient
+              $nodeName = $_
+              echo "Verifying connection $nodeName"
+              do
+              {
+                  try
+                  {
+                      echo "Trying to connect to $nodeName"
+                      $tcpClient.Connect($hashTable[$nodeName], 8080)
+                      echo "Connection to $nodeName successful"
+                  } catch 
+                  {
+                      if($startDate.AddMinutes(3) -lt (Get-Date)) 
+                      {
+                        throw "Unable to connect to $nodeName"
+                      }
+                      Start-Sleep -Seconds 2
+                  }
+              } While($tcpClient.Connected -ne "True")
+              $tcpClient.Close()
+              echo "Connection to $nodeName verified"
+          }
+
+          # Once you set the license on a node, it assumes the node to be a cluster, so only set the license on the leader
+          echo "Activating license on singlenode"
+          curl "http://$($fqdnRavenDB['singlenode']):8080/admin/license/activate" -H 'Content-Type: application/json; charset=UTF-8' -d "$($license)"
+
+          # Once you set the license on a node, it assumes the node to be a cluster, so only set the license on the leader
+          echo "Activating license on leader"
+          curl "http://$($fqdnRavenDB['leader']):8080/admin/license/activate" -H 'Content-Type: application/json; charset=UTF-8' -d "$($license)"
+
+          curl "http://$($fqdnRavenDB['leader']):8080/admin/license/set-limit?nodeTag=A&newAssignedCores=1" -X POST -H 'Content-Type: application/json; charset=utf-8' -H 'Content-Length: 0'
+          $encodedURL = [System.Web.HttpUtility]::UrlEncode("http://$($fqdnRavenDB['follower1']):8080") 
+          curl "http://$($fqdnRavenDB['leader']):8080/admin/cluster/node?url=$($encodedURL)&tag=B&watcher=true&assignedCores=1" -X PUT -H 'Content-Type: application/json; charset=utf-8' -H 'Content-Length: 0'
+          $encodedURL = [System.Web.HttpUtility]::UrlEncode("http://$($fqdnRavenDB['follower2']):8080")
+          curl "http://$($fqdnRavenDB['leader']):8080/admin/cluster/node?url=$($encodedURL)&tag=C&watcher=true&assignedCores=1" -X PUT -H 'Content-Type: application/json; charset=utf-8' -H 'Content-Length: 0'
+
+          $singlenodeurl = "http://$($fqdnRavenDB['singlenode']):8080"
+          echo "::set-output name=singlenodeurl::$singlenodeurl"
+          echo "::add-mask::$singlenodeurl"
+
+          $clusterurl = "http://$($fqdnRavenDB['leader']):8080,http://$($fqdnRavenDB['follower1']):8080,http://$($fqdnRavenDB['follower2']):8080"
+          echo "::set-output name=clusterurl::$clusterurl"
+          echo "::add-mask::$clusterurl"
+      - name: Encrypt Urls
+        run: |
+          # Unfortunately masking breaks job outputs so we go the extra mile
+          echo ${{ steps.setup-ravendb.outputs.singlenodeurl }} | gpg --quiet --symmetric --cipher-algo AES256 --batch --yes --passphrase '${{ secrets.PASSPHRASE }}' --output singlenodeurl.txt.gpg
+          echo ${{ steps.setup-ravendb.outputs.clusterurl }} | gpg --quiet --symmetric --cipher-algo AES256 --batch --yes --passphrase '${{ secrets.PASSPHRASE }}' --output clusterurl.txt.gpg
+      - name: Upload Urls
+        uses: actions/upload-artifact@v2
+        with:
+          name: ravendburls
+          path: |
+            singlenodeurl.txt.gpg
+            clusterurl.txt.gpg
+          retention-days: 1
+  build:
     name: ${{ matrix.name }}
     runs-on: ${{ matrix.os }}
+    needs: setup
     strategy:
       matrix:
         include:
@@ -30,77 +157,71 @@ jobs:
             name: Linux
       fail-fast: false
     steps:
-      - name: Check for secrets
-        env:
-          SECRETS_AVAILABLE: ${{ secrets.SECRETS_AVAILABLE }}
-        shell: pwsh
-        run: exit $(If ($env:SECRETS_AVAILABLE -eq 'true') { 0 } Else { 1 })
       - name: Checkout
         if: github.event_name != 'pull_request_target'
-        uses: actions/checkout@v2.3.4
+        uses: actions/checkout@v2.4.0
         with:
           fetch-depth: 0
       - name: Checkout for Dependabot
         if: github.event_name == 'pull_request_target'
-        uses: actions/checkout@v2.3.4
+        uses: actions/checkout@v2.4.0
         with:
           ref: 'refs/pull/${{ github.event.number }}/merge'
           fetch-depth: 0
       - name: Setup .NET SDK
-        uses: actions/setup-dotnet@v1.7.2
+        uses: actions/setup-dotnet@v1.8.2
         with:
           dotnet-version: 5.0.x
       - name: Setup .NET Core 3.1 runtime
-        uses: actions/setup-dotnet@v1.7.2
+        uses: actions/setup-dotnet@v1.8.2
         with:
           dotnet-version: 3.1.x
       - name: Build
         run: dotnet build src --configuration Release
       - name: Upload packages
         if: matrix.name == 'Windows'
-        uses: actions/upload-artifact@v2.2.2
+        uses: actions/upload-artifact@v2.2.4
         with:
           name: NuGet packages
           path: nugets/
           retention-days: 7
+      - name: Download Urls
+        uses: actions/download-artifact@v2
+        with:
+          name: ravendburls
+      - name: Prepare for tests
+        id: prepare
+        shell: pwsh
+        run: |
+          # Unfortunately masking breaks job outputs so we go the extra mile
+          gpg --quiet --batch --yes --decrypt --passphrase='${{ secrets.PASSPHRASE }}' --output singlenodeurl.txt singlenodeurl.txt.gpg
+          gpg --quiet --batch --yes --decrypt --passphrase='${{ secrets.PASSPHRASE }}' --output clusterurl.txt clusterurl.txt.gpg
+          $singlenodeurl = cat singlenodeurl.txt
+          echo "::add-mask::$singlenodeurl"
+          echo "::set-output name=singlenodeurl::$singlenodeurl"
+          $clusterurl = cat clusterurl.txt
+          echo "::add-mask::$clusterurl"
+          echo "::set-output name=clusterurl::$clusterurl"
+      - name: Run tests
+        env:
+          RavenSingleNodeUrl: ${{ steps.prepare.outputs.singlenodeurl }}
+          CommaSeparatedRavenClusterUrls: ${{ steps.prepare.outputs.clusterurl }}
+        uses: Particular/run-tests-action@v1.0.0
+
+  cleanup:
+    runs-on: ubuntu-20.04
+    if: ${{ always() }}
+    needs: [setup, build]
+    steps:
       - name: Azure login
-        uses: azure/login@v1.3.0
+        if: ${{ needs.setup.outputs.prefix != '' }}
+        uses: azure/login@v1.4.1
         with:
           creds: ${{ secrets.AZURE_ACI_CREDENTIALS }}
           enable-AzPSSession: true
-      - name: Setup RavenDB
-        id: setup-ravendb
-        shell: pwsh
-        run: |
-          $hostInfo = curl -H Metadata:true "169.254.169.254/metadata/instance?api-version=2017-08-01" | ConvertFrom-Json
-          $region = $hostInfo.compute.location
-          
-          $hostname = "psw-ravendb-$(Get-Random)"
-          echo "::set-output name=hostname::$hostname"
-          echo "Creating RavenDB container $hostname in $region (This can take a while.)"
-          $details = az container create --image ravendb/ravendb:4.2-ubuntu-latest  --name $hostname --location $region --dns-name-label $hostname --resource-group GitHubActions-RG --cpu 4 --memory 16 --ports 8080 38888 --ip-address public -e RAVEN_ARGS='--ServerUrl=http://0.0.0.0:8080 --Setup.Mode=None --License.Eula.Accepted=true --Security.UnsecuredAccessAllowed=PublicNetwork' | ConvertFrom-Json
-
-          $fqdn=$details.ipAddress.fqdn
-          echo "::add-mask::$fqdn"
-
-          echo "Tagging container image"
-          $dateTag = "Created=$(Get-Date -Format "yyyy-MM-dd")"
-          $ignore = az tag create --resource-id $details.id --tags Package=RavenPersistence RunnerOS=${{ runner.os }} $dateTag
-
-          echo "CommaSeparatedRavenClusterUrls=http://$($fqdn):8080" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
-      - name: Run Windows tests
-        if: matrix.name == 'Windows'
-        # -m:1 parameter prevents test projects from being run in parallel, which could cause conflicts since PessimisticLocks project shares same tests
-        run: dotnet test src --configuration Release --no-build --logger "GitHubActions;report-warnings=false" -m:1
-      - name: Run Linux tests
-        if: matrix.name == 'Linux'
-        # -m:1 parameter prevents test projects from being run in parallel, which could cause conflicts since PessimisticLocks project shares same tests
-        run: |
-          dotnet test src --configuration Release --no-build --framework netcoreapp3.1 --logger "GitHubActions;report-warnings=false" -m:1
-          dotnet test src --configuration Release --no-build --framework net5.0 --logger "GitHubActions;report-warnings=false" -m:1
       - name: Teardown RavenDB
-        if: ${{ always() }}
+        if: ${{ needs.setup.outputs.prefix != '' }}
         uses: Azure/powershell@v1
         with:
-          inlineScript: Remove-AzContainerGroup -ResourceGroupName GitHubActions-RG -Name ${{ steps.setup-ravendb.outputs.hostname }}
-          azPSVersion: latest
+          inlineScript: Get-AzContainerGroup -ResourceGroupName GitHubActions-RG | Where-Object { $_.Name -like "${{ needs.setup.outputs.prefix }}*" } | Remove-AzContainerGroup | Out-Null
+          azPSVersion: latest      
